sersh: option B improperly consuming next option, remove it
getopt.getopt() option string contained 'B:' instead of 'B', so
the following option was being consumed.  -B/--basic does not have
any impact on sersh, so just remove it as a valid option.

  $ sersh -B ttyACM2 'ls -l /home/serio-test'
  ERROR: could not open port /dev/ls: [Errno 2] No such file or directory: '/dev/ls'
  $ sersh  ttyACM2 'ls -l /home/serio-test'
  total 4
  -rw-r--r-- 1 root root 2 Feb  6 04:47 a

Signed-off-by: Frank Rowand <frowand.list@gmail.com>